--- 
 JOB_ID: "fedem-noniid"
 API_VER: standard
 PARAMS:
   mnist-num-layers: 6
   num-clusters: 5
   update-center-every: 1
   num-rounds: 80
   epochs: 10
   eval-every: 10
   clients-per-round: 6 
   batch-size: 10
   lr: 0.01
   seed: 514306
   regul-term: 0.1
   mu: 0.1
   mode: 'no_size'
   poisoning: on
   num_agents: 0.1
   exp-seeds: 
     - 322778
 EXPORT:
   history-file: ''
